/**
 * markdownFormatter.js
 * Converts the validated AI JSON response into a GitHub-flavored markdown comment.
 */

const config = require('../utils/config');

/**
 * Formats a parsed AI response into a markdown comment string.
 *
 * @param {{
 *   issue_type: string,
 *   priority: string,
 *   priority_reason: string,
 *   severity: string,
 *   confidence: string,
 *   enhanced_issue: Record<string, string>,
 *   missing_information: string[],
 *   suggested_labels: string[],
 * }} parsed
 * @returns {string} Markdown-formatted comment body.
 */
function formatComment(parsed) {
  const {
    issue_type, priority, priority_reason, severity, confidence,
    enhanced_issue, missing_information, suggested_labels,
  } = parsed;
  const typeDisplay = formatIssueType(issue_type);

  const issueFieldsBlock = buildIssueFieldsBlock(issue_type, enhanced_issue);

  const missingBlock =
    missing_information.length > 0
      ? missing_information.map((item) => `- ${capitalise(item)}`).join('\n')
      : '_No missing information detected._';

  const labelsBlock =
    suggested_labels.length > 0
      ? suggested_labels.map((label) => `\`${label}\``).join('  ')
      : '_No labels suggested._';

  return `## AI Issue Enhancement

> **Detected Type:** ${typeDisplay}
> **Priority:** ${capitalise(priority || 'medium')}
> **Priority Reason:** ${priority_reason || 'Not specified'}
> **Severity:** ${capitalise(severity || 'medium')}
> **Confidence:** ${capitalise(confidence || 'medium')}

---

### Structured Issue

${issueFieldsBlock}

---

### Missing Information

${missingBlock}

---

### Suggested Labels

${labelsBlock}

---

<sub>Generated by [IssueCraft](https://github.com/marketplace) - Prompt v${config.prompt.version}</sub>
`;
}

function buildIssueFieldsBlock(issueType, enhancedIssue) {
  const fieldOrderByType = {
    bug: ['title', 'summary', 'steps_to_reproduce', 'observed_behavior', 'expected_behavior'],
    feature_request: ['title', 'summary', 'proposed_feature', 'expected_outcome', 'expected_impact'],
    documentation: ['title', 'summary', 'affected_docs', 'suggested_change'],
    performance: ['title', 'summary', 'current_performance', 'expected_performance', 'environment'],
    improvement: ['title', 'summary', 'current_limitation', 'proposed_improvement', 'expected_outcome'],
    ui_ux: ['title', 'summary', 'current_experience', 'expected_experience', 'user_impact', 'design_reference'],
    other: ['title', 'summary', 'observed_behavior', 'expected_behavior'],
  };

  const fields = fieldOrderByType[issueType] || fieldOrderByType.other;
  return fields
    .map((field) => `**${formatFieldLabel(field)}**\n${formatFieldValue(field, enhancedIssue[field])}`)
    .join('\n\n');
}

function formatFieldLabel(field) {
  return field
    .split('_')
    .map((part) => capitalise(part))
    .join(' ');
}

function formatIssueType(type) {
  const map = {
    bug: 'Bug',
    feature_request: 'Feature Request',
    improvement: 'Improvement',
    ui_ux: 'UI / UX',
    documentation: 'Documentation',
    performance: 'Performance',
    other: 'Other',
  };
  return map[type] || 'Other';
}

function capitalise(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function formatFieldValue(field, value) {
  const safeValue = String(value || 'Not specified').trim() || 'Not specified';
  if (field !== 'steps_to_reproduce') return safeValue;
  return formatSteps(safeValue);
}

function formatSteps(steps) {
  if (steps.toLowerCase() === 'not specified') return steps;

  const candidates = steps
    .split(/[\r\n]+|,\s*/)
    .map((step) => step.trim())
    .map((step) => step.replace(/^[-*]\s+/, ''))
    .map((step) => step.replace(/^\d+[.)]\s+/, ''))
    .map((step) => step.replace(/[;,]+$/g, '').trim())
    .filter(Boolean);

  const actionableCandidates = candidates.filter((step) => isLikelyActionableStep(step));
  if (actionableCandidates.length < 2) return steps;

  return actionableCandidates
    .map((step, index) => `${index + 1}. ${step}`)
    .join('\n');
}

function isLikelyActionableStep(step) {
  return /^(open|go|navigate|visit|click|tap|select|choose|enter|type|submit|press|log in|login|upload|download|install|run|refresh|restart|create|update|delete|save)\b/i.test(step);
}

module.exports = { formatComment };
