/**
 * markdownFormatter.js
 * Converts the validated AI JSON response into a GitHub-flavoured markdown comment.
 */

/**
 * Formats a parsed AI response into a markdown comment string.
 *
 * @param {{
 *   issue_type: string,
 *   enhanced_issue: {
 *     title: string,
 *     summary: string,
 *     steps_to_reproduce: string,
 *     observed_behavior: string,
 *     expected_behavior: string,
 *   },
 *   missing_information: string[],
 *   suggested_labels: string[],
 * }} parsed
 * @returns {string} Markdown-formatted comment body.
 */
function formatComment(parsed) {
  const { issue_type, enhanced_issue, missing_information, suggested_labels } = parsed;

  const typeDisplay = formatIssueType(issue_type);

  // ── Missing information block ──────────────────────────────────────────────
  const missingBlock =
    missing_information.length > 0
      ? missing_information.map((item) => `- ${capitalise(item)}`).join('\n')
      : '_No missing information detected._';

  // ── Labels block ───────────────────────────────────────────────────────────
  const labelsBlock =
    suggested_labels.length > 0
      ? suggested_labels.map((label) => `\`${label}\``).join('  ')
      : '_No labels suggested._';

  const comment = `## 🤖 AI Issue Enhancement

> **Detected Type:** ${typeDisplay}

---

### ✏️ Improved Issue

**Title**
${enhanced_issue.title}

**Summary**
${enhanced_issue.summary}

**Steps to Reproduce**
${enhanced_issue.steps_to_reproduce}

**Observed Behavior**
${enhanced_issue.observed_behavior}

**Expected Behavior**
${enhanced_issue.expected_behavior}

---

### ⚠️ Missing Information

${missingBlock}

---

### 🏷️ Suggested Labels

${labelsBlock}

---

<sub>Generated by [AI Issue Enhancer](https://github.com/marketplace) · Prompt v${require('../utils/config').prompt.version}</sub>
`;

  return comment;
}

/**
 * Turns an issue_type key into a human-readable display string.
 * @private
 */
function formatIssueType(type) {
  const map = {
    bug:             '🐛 Bug',
    feature_request: '✨ Feature Request',
    improvement:     '🔧 Improvement',
    ui_ux:           '🎨 UI / UX',
    documentation:   '📄 Documentation',
    performance:     '⚡ Performance',
    other:           '🔍 Other',
  };
  return map[type] || '🔍 Other';
}

function capitalise(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

module.exports = { formatComment };
